[package]
name = "term-clock"
version = "0.1.0"
authors = ["hellojukay <hellojukay@hellojukay@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
figlet-rs= "0.1.3"
chrono = "0.4"
console= "0.14.1"
